### ISSUE TITLE
app.js not found

### ISSUE THREAD

**Issue by felipeparente** [ishanvyas22/cakephp-vuejs-skeleton#19]
I carried out the entire process, but when accessing http://localhost/cakephp-vuejs-app/pages/greet
I receive the following error message:

Unable to locate AssetMix file: /cakephp-vuejs-app/js/app.js.

**Comment by felipeparente** [comment]
I managed to run it, but it only works if I run the cake server "bin/cake server", otherwise it gives an error.
Can they run on my Apache or Nginx installed on the machine?

**Comment by felipeparente** [comment]
I managed to get around it, here's the tip:

<?= $this->AssetMix->script($this->Url->build('/js/app.js', ['fullBase' => true])) ?>

**Comment by felipeparente** [comment]
I managed to get around it, here's the tip:

`
<?php echo $this->AssetMix->script($this->Url->build('/js/app.js', ['fullBase' => true])) ?>
`

**Comment by felipeparente** [comment]
I managed to get around it, here's the tip:

`$this->AssetMix->script($this->Url->build('/js/app.js', ['fullBase' => true]))`

**Comment by ishanvyas22** [comment]
I see you are serving application from sub directory, in that case you have to update your `App.base` config to set the subdir there.
